SoundBase/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('musicplay.urls')),
    url(r'^accounts/', include('allauth.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

musicplay/urls.py
from django.conf.urls import url
from . import views

app_name = 'musicplay'

urlpatterns = [

    url(r'^$', views.indexview, name='index'),
    url(r'^albums$', views.albumsview, name='albums'),
    url(r'^song/(?P<pk>[0-9]+)/$', views.SongDetailView.as_view(), name='songdetail'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumDetailView, name='albumdetail'),
    url(r'^song/add/$', views.AddSongView, name='add_song'),
    url(r'^album/add/$', views.AddAlbumview, name='add_album'),
    url(r'song/(?P<pk>[0-9]+)/update/$', views.SongUpdate.as_view(), name='song_update'),
    url(r'song/(?P<pk>[0-9]+)/delete/$', views.SongDelete.as_view(), name='song_delete'),
    url(r'album/(?P<pk>[0-9]+)/update/$', views.AlbumUpdate.as_view(), name='album_update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album_delete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^api/songs/$', views.songs_list_api.as_view(), name='songlistapi'),
    url(r'^api/songs/(?P<pk>[0-9]+)/$', views.songs_detail_api.as_view(), name='songdetailapi')
]

musicplay/models.py
from django.db import models
from django.urls import reverse

RATINGS_CHOICE = (('1 STAR','1 STAR'),('2 STAR','2 STAR'),('3 STAR','3 STAR'),('4 STAR','4 STAR'),('5 STAR','5 STAR'))

class Song(models.Model):
    song_title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    artiste = models.CharField(max_length=100)
    album = models.ForeignKey('Album', on_delete=models.SET_NULL, null=True)
    genre = models.CharField(max_length=100)
    release_year = models.CharField(max_length=4)
    rating = models.CharField(max_length=6, choices=RATINGS_CHOICE, default='1 STAR' )
    song_file = models.FileField(upload_to='songs')
    song_art = models.FileField(upload_to='song_art')
    uploaded_by = models.CharField(max_length=25, default='uploader', blank=True)

    def get_absolute_url(self):
        return reverse('musicplay:songdetail', kwargs={'pk':self.pk})

    def __str__(self):
        return (self.song_title)

class Album (models.Model):
    album_title = models.CharField(max_length=100)
    slug = models.SlugField()
    artiste = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    release_year = models.CharField(max_length=4)
    rating = models.CharField(max_length=6, choices=RATINGS_CHOICE, default='1 STAR')
    album_art = models.FileField(upload_to='album_art')
    uploaded_by = models.CharField(max_length=25, default='uploader', blank=True)

    def __str__(self):
        return (self.album_title)


    def get_absolute_url(self):
        return reverse('musicplay:albumdetail', kwargs={'pk':self.pk})

musicplay/forms.py
from django.forms import ModelForm
from .models import *

class AddSongForm(ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'artiste', 'album', 'genre', 'release_year', 'rating', 'song_file', 'song_art']

class AddAlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['album_title', 'artiste', 'genre', 'release_year', 'rating', 'album_art']

templates/musicplay/add_album.html
{% extends 'musicplay/form_template.html' %}
{% block title %} Add an Album {% endblock %}

{% block wizardcontainer %}
  <div class="wizard-container">

		                <div class="card wizard-card" data-color="orange" id="wizardProfile">
		                    <form action="" method="post" enctype="multipart/form-data">
		                <!--        You can switch " data-color="orange" "  with one of the next bright colors: "blue", "green", "orange", "red", "azure"          -->

		                    	<div class="wizard-header text-center">
		                        	<h3 class="wizard-title">Add an Album</h3>
		                    	</div>
                                {% if user.is_authenticated %}
								<div class="wizard-navigation">
									<div class="progress-with-circle">
									     <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
									</div>
									<ul>
			                            <li>
											<a href="#page1" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-user"></i>
												</div>
												About
											</a>
										</li>
			                            <li>
											<a href="#page2" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-settings"></i>
												</div>
												Work
											</a>
										</li>
			                            <li>
											<a href="#page3" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-map"></i>
												</div>
												Address
											</a>
										</li>
			                        </ul>
								</div>
		                        <div class="tab-content">
		                            <div class="tab-pane" id="page1">
		                            	<div class="row">

                                            {% load widget_tweaks %}
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8">

                                                {{ addalbumform.errors }}
                                                    <div class="form-group">
                                                        <label>Song Title <small>(required)</small></label>
                                                         {{ addalbumform.album_title|attr:"class:form-control"|attr:"placeholder:Song Title"  }}
                                                    </div>
                                                    <div class="form-group">
                                                        <label>Artiste <small>(required)</small></label>
                                                          {{ addalbumform.artiste|attr:"class:form-control"|attr:"placeholder:Artiste"  }}
                                                    </div>
                                                      {% csrf_token %}
                                            </div>
                                        <div class="col-md-2"></div>
                                        </div>

		                            </div>
                                    <div class="tab-pane" id="page2">
		                                <h5 class="info-text"> What are you doing? (checkboxes) </h5>
		                                <div class="row">
		                                    <div class="col-sm-8 col-sm-offset-2">
		                                        <div class="form-group">
                                                            <label>Genre <small>(required)</small></label>
                                                            {{ addalbumform.genre|attr:"class:form-control"|attr:"placeholder:Genre"  }}
                                                    </div>
                                                 <div class="form-group">
                                                        <label>Release Year <small>(required)</small></label>
                                                        {{ addalbumform.release_year|attr:"class:form-control"|attr:"placeholder:Release Year"  }}
                                                </div>
                                                 <div class="form-group">
                                                        <label>Rating <small>(required)</small></label>
                                                        {{ addalbumform.rating|attr:"class:form-control"|attr:"placeholder:Rating"  }}
                                                </div>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="tab-pane" id="page3">
		                                <div class="row">
		                                    <div class="col-sm-12">
		                                        <h5 class="info-text"> Are you living in a nice area? </h5>
		                                    </div>
                                            <div class="form-group">
                                                    <label>Upload Song Art <small>(required)</small></label>
                                                    {{ addalbumform.album_art|attr:"placeholder:Upload Song Art"  }}
                                            </div>
                                                </div>
		                            </div>
		                        </div>
                                <div class="wizard-footer">
		                            <div class="pull-right">
		                                <input type='button' class='btn btn-next btn-fill btn-warning btn-wd' name='next' value='Next' />
                                        <button type='submit' class='btn btn-finish btn-fill btn-warning btn-wd' name='finish' value='Finish'>Button </button>
		                            </div>

		                            <div class="pull-left">
		                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
		                            </div>
		                            <div class="clearfix"></div>
		                        </div>
                                    {% else %}
                                    <h5 class="text-center"> <a href="{% url 'account_login' %}">  You are not allowed to perform this action. Login to upload a song </a></h5>
                                {% endif %}

		                    </form>
		                </div>
		            </div> <!-- wizard container -->
{% endblock %}

templates/musicplay/albumdetail.html
{%  extends 'musicplay/details.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SoundBase: {{ albumdetails }}</title>
</head>


<body>
{% block breadcrumb %} <h5 class="breadcrumb"> SoundBase > Songs > {{ albumdetails }} </h5> {% endblock %}

{% block songdetails %}
        <div class="col-md-9">
           <div class="col-md-6"> <img class="img-details "  src="/media/{{ albumdetails.album_art }}"></div>
               <div class="col-md-6 song-details">
                   <li><h4> <span class="glyphicon glyphicon-folder-close"></span> &nbsp; &nbsp;{{ albumdetails }}</h4> </li>
                   <li><a> <span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;{{ albumdetails.artiste }}</a> </li>
                  <li> <a> <span class="glyphicon glyphicon-tag"></span>&nbsp;{{ albumdetails.genre }}</a></li>

               {% if user.is_authenticated %}

                    <li><a type="button" class="btn btn-primary" href="{% url 'musicplay:album_update' albumdetails.id %}"><span class="glyphicon glyphicon-edit"></span>Update Album</a> </li>

                   <form action="{% url 'musicplay:album_delete' albumdetails.id %}" method="post">
                       {% csrf_token %}
                       <button class="btn btn-danger"> <span class="glyphicon glyphicon-trash"></span> Delete Album </button>
                   </form>

                   {% else %}

                   <a>You are not allowed to perfrom any actions on this album</a>

               {% endif %}

                   <h4>Songs</h4>
                   {% for song in albumsongs %}
                       <li><a class="text-center" href="{% url 'musicplay:songdetail' song.id %}"> <span class="glyphicon glyphicon-music"></span> {{ song }}</a> </li>
                   {% endfor %}

               </div>
        </div>
    {% endblock %}

</body>
</html>

templates/musicplay/albums.html
{% extends 'musicplay/base.html' %}<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>SoundBase: Base of Good Music</title>
    {% endblock %}
</head>
<body>
{% block breadcrumb %} <h5 class="breadcrumb"> SoundBase > Albums </h5> {% endblock %}
{% block body %}
{% for album in all_albums %}
     <div class="col-md-4">
            <a href="{% url 'musicplay:albumdetail' album.id %}"><img class="imgeffect"  src="../media/{{ album.album_art }}"> <span class="viewdetails"></span></a><br>
                 <h5 class="text-center" href="{% url 'musicplay:albumdetail' album.id %}"> <span class="glyphicon glyphicon-music"></span> {{ album }}</h5>
                 <h5 class="text-center"> <span class="glyphicon glyphicon-user"></span> {{ album.artiste }}</h5>
            </div>

{% endfor %}
{% endblock %}
</body>
</html>

templates/musicplay/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		{% block title %}
        <title>SoundBase: Base of Good Music</title>
        {% endblock %}
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="/static/css/styles.css" rel="stylesheet">
		<link href="/static/css/bootstrap.css" rel="stylesheet">


        <link href="/static/css/font-awesome.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="/static/css/styles.css" rel="stylesheet">
	</head>
	<body>

<header class="navbar navbar-default navbar-static-top" role="banner">
  <div class="container ">

    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand"><span class="fa fa-music"></span> SoundBase</a>
    </div>

    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'musicplay:index' %}">Songs</a>
        </li>
        <li>
          <a href="{% url 'musicplay:albums' %}">Albums</a>
        </li>
        <li>
          <a href="{% url 'musicplay:add_song' %}"><span class="fa fa-plus-square"></span>&nbsp; Add Song</a>
        </li>
        <li>
          <a href="{% url 'musicplay:add_album' %}"><span class="fa fa-plus-square"></span>&nbsp; Add Album</a>
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right list-inline accountnav">
            {% if user.is_authenticated %}
            <li>
              <a>Hi, {
                  { user.username }}</a>
            </li>

            <li>
              <a href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li>
              <a href="{% url 'account_set_password' %}">Set Password</a>
            </li>
            <li>
                {% else %}
                <li>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            <li>
              <a href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
  </div>
</header>

<!-- Begin Body -->
<div class="container margin-container">
	<div class="row">
           {% block breadcrumb %} <h5 class="breadcrumb"> SoundBase > Songs </h5> {% endblock %}
    {% block topratings %}
  			<div class="col-md-3" id="leftCol">

				<div class="well sidebar">
              	<ul class="nav nav-stacked" id="sidebar">

                {# Recent Uploads #}
                <li> <a class="btn btn-success" >  <span class="glyphicon glyphicon-time"></span>  &nbsp; Recent uploads</a> </li>
                    {% for song in latestsongs %}
                  <li>  <a class="ratingstext" href="{% url 'musicplay:songdetail' song.id %}"> <span class="glyphicon glyphicon-music"></span> {{ song }}</a></li>
                    {% endfor %}

                {# Top Songs #}
                  <li><a class="btn btn-danger" >  <span class="glyphicon glyphicon-music"></span>  &nbsp;Top Songs</a></li>
                        {% for song in songtopratings %}
                          <li> <a class ="ratingstext"  href="{% url 'musicplay:songdetail' song.id %}" >{{ song }}
                              {% if song.rating == '5 STAR' %}
                                  {% for star in 5star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if song.rating == '4 STAR' %}
                                  {% for star in 4star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if song.rating == '3 STAR' %}
                                  {% for star in 3star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}&nbsp;
                          </a> </li>
                        {% endfor %}

                {# Top Albums #}

                   <li> <a class="btn btn-success" >  <span class="glyphicon glyphicon-folder-close"></span>  &nbsp; Top Albums</a> </li>
                        {% for album in albumtopratings %}
                              <li>  <a class="ratingstext" href="{% url 'musicplay:albumdetail' album.id %}">
                                  {% if album.rating == '5 STAR' %}
                                  {% for star in 5star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if album.rating == '4 STAR' %}
                                  {% for star in 4star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if album.rating == '3 STAR' %}
                                  {% for star in 3star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}&nbsp;{{ album }}
                              </a> </li>

                        {% endfor %}

                </ul>
  				</div>


      		</div>
    {% endblock %}
                <div class="col-md-9">
                    {% block body %}
                    {% endblock %}
      		    </div>
  	</div>
</div>


	<!-- script references -->
		<script src="../../static/js/jquery.min.js"></script>
		<script src="../../static/js/bootstrap.min.js"></script>
		<script src="../../static/js/scripts.js"></script>
	</body>
    <footer class="modal-footer"><a class="leftfooter">  <span class="glyphicon glyphicon-copyright-mark"></span>  SoundBase 2017 </a><a href="http://plansharetech.com"> Delicately Crafted by  PlanShare Technolgies <a/></footer>
</html>

templates/musicplay/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="row">
    <div class="col-md-6">
        <a> Column 1</a>
    </div>
    <div class="col-md-6">
        Column 2
    </div>
</div>


</body>

<script src="../../static/js/bootstrap.min.js"></script>
</html>

templates/musicplay/details.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		{% block title %}
        <title>SoundBase: Base of Good Music</title>
        {% endblock %}
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/font-awesome.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="/static/css/styles.css" rel="stylesheet">
	</head>
	<body>

<header class="navbar navbar-default navbar-static-top" role="banner">
  <div class="container">

    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand"><span class="fa fa-music"></span> SoundBase</a>
    </div>

    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'musicplay:index' %}">Songs</a>
        </li>
        <li>
          <a href="{% url 'musicplay:albums' %}">Albums</a>
        </li>
        <li>
          <a href="{% url 'musicplay:add_song' %}"><span class="fa fa-plus-square"></span>&nbsp; Add Song</a>
        </li>
        <li>
          <a href="{% url 'musicplay:add_album' %}"><span class="fa fa-plus-square"></span>&nbsp; Add Album</a>
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right list-inline accountnav">
            {% if user.is_authenticated %}
            <li>
              <a>Hi, {{ user.username }}</a>
            </li>

            <li>
              <a href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li>
              <a href="{% url 'account_set_password' %}">Set Password</a>
            </li>
            <li>
                {% else %}
                <li>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            <li>
              <a href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
  </div>
</header>


<!-- Begin Body -->
<div class="container margin-container">
	<div class="row">
           {% block breadcrumb %} <h5 class="breadcrumb"> SoundBase > Songs </h5> {% endblock %}
    {% block topratings %}
  			<div class="col-md-3" id="leftCol">
              	
				<div class="well sidebar">
              	<ul class="nav nav-stacked" id="sidebar">

                {# Recent Uploads #}
                <li> <a  class="btn btn-success"  >  <span class="glyphicon glyphicon-time"></span>  &nbsp; Recent uploads</a> </li>
                    {% for song in latestsongs %}
                  <li>  <a class="ratingstext" href="{% url 'musicplay:songdetail' song.id %}"> <span class="glyphicon glyphicon-music"></span> {{ song }}</a></li>
                    {% endfor %}

                {# Top Songs #}
                  <li><a  class="btn btn-danger" >  <span class="glyphicon glyphicon-music"></span>  &nbsp;Top Songs</a></li>
                        {% for song in songtopratings %}
                          <li> <a class ="ratingstext"  href="{% url 'musicplay:songdetail' song.id %}" >{{ song }}
                              {% if song.rating == '5 STAR' %}
                                  {% for star in 5star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if song.rating == '4 STAR' %}
                                  {% for star in 4star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if song.rating == '3 STAR' %}
                                  {% for star in 3star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}&nbsp;
                          </a> </li>
                        {% endfor %}

                {# Top Albums #}

                   <li> <a class="btn btn-success">  <span class="glyphicon glyphicon-folder-close"></span>  &nbsp; Top Albums</a> </li>
                        {% for album in albumtopratings %}
                              <li>  <a class="ratingstext" href="{% url 'musicplay:albumdetail' album.id %}">
                                  {% if album.rating == '5 STAR' %}
                                  {% for star in 5star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if album.rating == '4 STAR' %}
                                  {% for star in 4star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}
                              {% if album.rating == '3 STAR' %}
                                  {% for star in 3star %}
                                      <span style="color: gold; float: right" class="fa fa-star"></span>
                                  {% endfor %}{% endif %}&nbsp;{{ album }}
                              </a> </li>

                        {% endfor %}

                </ul>
  				</div>


      		</div>
    {% endblock %}
    {% block songdetails %}
        <div class="col-md-9">
           <div class="col-md-6"> <img class="img-details "  src="/media/{{ songdetails.song_art }}"></div>
               <div class="col-md-6 song-details">
                   <li><a> <span class="glyphicon glyphicon-music"></span> &nbsp; &nbsp;{{ songdetails }}</a> </li>
                   <li><a> <span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;{{ songdetails.artiste }}</a> </li>
                  <li> <a> <span class="glyphicon glyphicon-tag"></span>&nbsp;{{ songdetails.genre }}</a></li>
                   <li><a href="{% url 'musicplay:albumdetail' songdetails.album.id %}"> <span class="glyphicon glyphicon-folder-close"></span>&nbsp;&nbsp;{{ songdetails.album }}</a></li>
                  <li> <audio controls="controls" src="/media/{{ songdetails.song_file }}"></audio> </li>


                   {% if user.is_authenticated %}

                    <a  class="btn btn-primary" href="/media/{{ songdetails.song_file }}">
                      <span class="glyphicon glyphicon-download"></span> Download Song
                    </a>

                   <a class="btn btn-primary" href="{% url 'musicplay:song_update' songdetails.id %}">
                      <span class="glyphicon glyphicon-edit"></span> Update Song
                    </a>

                   <form action="{% url 'musicplay:song_delete' songdetails.id %}" method="post" >
                  {% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                      <span class="glyphicon glyphicon-trash"></span> Delete Song
                    </button>
                    </form>

                       {% else %}

                       <a href="{% url 'account_login' %}"> You are not allowed to perform any further actions on this song. You need to Login</a>

                   {% endif %}

               </div>
        </div>
    {% endblock %}
</div>

</div>


	<!-- script references -->
		<script src="../../static/js/jquery.min.js"></script>
		<script src="../../static/js/bootstrap.min.js"></script>
		<script src="../../static/js/scripts.js"></script>
	</body>
    <footer class="modal-footer"><a class="leftfooter">  <span class="glyphicon glyphicon-copyright-mark"></span>  SoundBase 2017 </a><a href="http://plansharetech.com"> Delicately Crafted by  PlanShare Technolgies <a/></footer>
</html>

templates/musicplay/form_template.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<link rel="apple-touch-icon" sizes="76x76" href="/static/wizard/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="/static/wizard/img/favicon.png" />
	<title>SoundBase: {% block title %} {% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<!-- CSS Files -->
    <link href="/static/wizard/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/static/wizard/css/paper-bootstrap-wizard.css" rel="stylesheet" />

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="/static/wizard/css/demo.css" rel="stylesheet" />

	<!-- Fonts and Icons -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="/static/wizard/css/themify-icons.css" rel="stylesheet">
</head>

<body>
	<div class="image-container set-full-height" style="background-image: url('/static/img/back1.jpg')">
	    <!--   Creative Tim Branding   -->
	    <a href="{% url 'musicplay:index' %}">
	         <div class="logo-container">
	            <div class="brand">
	                SoundBase
	            </div>
	        </div>
	    </a>

		<!--  Made With Paper Kit  -->
		<a href="http://demos.creative-tim.com/paper-kit?ref=paper-bootstrap-wizard" class="made-with-pk">
			<div class="brand">PS</div>
			<div class="made-with">Planshare <strong>Technologies</strong></div>
		</a>

	    <!--   Big container   -->
	    <div class="container">
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">
                {% block wizardcontainer %}

                {% endblock %}
		        </div>
	        </div> <!-- row -->
	    </div> <!--  big container -->

	    <div class="footer">
	        <div class="container text-center">
	             Made with <i class="fa fa-heart heart"></i> by <a href="http://www.plansharetech.com">PlanShare Technologies</a>
            </div>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="/static/wizard/js/jquery-2.2.4.min.js" type="text/javascript"></script>
	<script src="/static/wizard/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="/static/wizard/js/jquery.bootstrap.wizard.js" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="/static/wizard/js/paper-bootstrap-wizard.js" type="text/javascript"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="/static/wizard/js/jquery.validate.min.js" type="text/javascript"></script>

</html>

templates/musicplay/search.html
{% extends 'musicplay/base.html' %}


{% block body %}
<form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
{% for song in filter.qs %}
    {{ song }}
{% endfor %}
{% endblock %}

templates/musicplay/songdetail.html
{% extends 'musicplay/details.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SoundBase: {{ songdetails }}</title>
</head>
<body>
{% block breadcrumb %} <h5 class="breadcrumb"> SoundBase > Songs > {{ songdetails }} </h5> {% endblock %}

</body>
</html>